language: cpp

dist: trusty

notifications:
  email: false

matrix:
  include:
  # # # # # # # # #
  # x86_64 builds #
  # # # # # # # # #

  # Linux - gcc 7 + coverage
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && GCOV=gcov-7"
        - COVERAGE=ON
        - ARCH=x64

  # Linux - gcc 7
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - ARCH=x64

  # Linux - gcc 8
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        - ARCH=x64

  # Linux - clang 5
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-5.0
            - g++-7
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
        - ARCH=x64

  # Linux - clang 6
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-6.0
            - g++-7
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
        - ARCH=x64

  # # # # # # # #
  # x86  builds #
  # # # # # # # #

  # Linux - gcc 7
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7-multilib
            - libc6-dev:i386
            - linux-libc-dev:i386
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - ARCH=x86

  # Linux - gcc 8
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8-multilib
            - libc6-dev:i386
            - linux-libc-dev:i386
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        - ARCH=x86

  # Linux - clang 5
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-5.0
            - g++-7-multilib
            - libc6-dev:i386
            - linux-libc-dev:i386
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
        - ARCH=x86

  # Linux - clang 6
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-6.0
            - g++-7-multilib
            - libc6-dev:i386
            - linux-libc-dev:i386
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
        - ARCH=x86

before_install:
  - |
    eval "${MATRIX_EVAL}"
    if [[ -v COVERAGE ]]; then
      wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.13.orig.tar.gz
      tar xf lcov_1.13.orig.tar.gz
      sudo make -C lcov-1.13/ install
    fi
    chmod a+x .travis/*

script:
  - .travis/build.sh

after_success:
  - .travis/codecov.sh
