language: cpp

dist: trusty

notifications:
  email: false

matrix:
  include:
  # # # # # # # # #
  # x86_64 builds #
  # # # # # # # # #

  # Linux - gcc 7 + coverage
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && GCOV=gcov-7"
        - COVERAGE=ON

  # Linux - gcc 7
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

  # Linux - gcc 8
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

  # Linux - clang 5
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-5.0
            - g++-7
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

  # Linux - clang 6
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-6.0
            - g++-7
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"


before_install:
  - eval "${MATRIX_EVAL}"
  - |
    if [[ -v COVERAGE ]]; then
      wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.13.orig.tar.gz
      tar xf lcov_1.13.orig.tar.gz
      sudo make -C lcov-1.13/ install
    fi

script:
  - |
    if [[ -v COVERAGE ]]; then
      cmake . -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Coverage && make
      echo -e "\n\t\tINITIALIZING LCOV ENVIRONMENT\n"
      lcov --version
      lcov -d . --zerocounters
      lcov -c -i -d . -o coverage_base.info --gcov-tool '/usr/bin/gcov-7' --no-external
      lcov --remove coverage_base.info '/usr/*' 'third-party/catch.hpp' 'test/test_ram.cpp' 'test/test_cp1.cpp' -o coverage_base.info
      lcov --list coverage_total.info
      echo -e "\n\t\tRUNNING TESTS\n"
      ctest -C Debug --output-on-failure
    else
      cmake . -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug && make && file Tests && ctest -C Debug --output-on-failure
      cmake . -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release && make && file Tests && ctest -C Release --output-on-failure
    fi

after_success:
  - |
    if [[ -v COVERAGE ]]; then
      echo -e "\n\t\tRUNNING LCOV AFTER TESTS\n"
      lcov -d . -c -o coverage_test.info --gcov-tool '/usr/bin/gcov-7' --no-external
      lcov -r coverage_base.info '/usr/*' 'third-party/catch.hpp' 'test/test_ram.cpp' 'test/test_cp1.cpp' -o coverage_test.info
      lcov -a coverage_base.info -a coverage_test.info -o coverage_total.info
      rm coverage_base.info coverage_test.info
      lcov --list coverage_total.info
      echo -e "\n\t\tUPLOADING TO CODECOV\n"
      bash <(curl -s https://codecov.io/bash) -X coveragepy -x "/usr/bin/gcov-7"
    fi