language: cpp

dist: trusty

notifications:
  email: false

matrix:
  include:
  # Linux - gcc 7
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  # Linux - clang 4
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
  # Linux - clang 5
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
  # Linux - clang 6
      - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    cmake . -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug && make && make test
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    cmake . -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release && make && make test
    fi
  