language: cpp

dist: trusty

notifications:
  email: false

matrix:
  include:
  # Linux - gcc 7 + coverage
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gcov-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && GCOV=gcov-7"
        - COVERAGE=ON

  # Linux - gcc 7
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  # Linux - gcc 8
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
  # Linux - clang 5
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-5.0
            - g++-7
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
  # Linux - clang 6
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-6.0
            - g++-7
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
        

before_install:
  - bash --version
  - eval "${MATRIX_EVAL}"
  - gcc --version
  - gcov --version
  - |
    if [[ -v COVERAGE ]]; then
      wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.13.orig.tar.gz
      tar xf lcov_1.13.orig.tar.gz
      sudo make -C lcov-1.13/ install
    fi

script:
  - |
    if [[ -v COVERAGE ]]; then
      cmake . -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Coverage && make && ctest -C Debug --output-on-failure
    else
      cmake . -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug && make && ctest -C Debug --output-on-failure
      cmake . -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release && make && ctest -C Release --output-on-failure
    fi

after_success:
  - |
    if [[ -v COVERAGE ]]; then
      lcov --directory ${TRAVIS_BUILD_DIR} --capture --output-file coverage.info --gcov-tool /usr/bin/gcov-7
      lcov --remove coverage.info '/usr/*' '${TRAVIS_BUILD_DIR}/third-party/*' --output-file coverage.info 
      lcov --list coverage.info
      bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
    fi