version: '0.1.{build}'

branches:
  only:
    - master
    - develop

image: Visual Studio 2017

configuration:
  - Debug
  - Release

platform:
  - x64

before_build:
- cmd: |-
    mkdir build
    cd build
    cmake --version
    cmake .. -G "Visual Studio 15 2017 Win64"
build:
  project: c:\projects\MIPS32\build\MIPS32.sln
  verbosity: minimal
  parallel: true

test_script:
  - c:\projects\MIPS32\x64\Debug\my_test.exe
  - c:\projects\MIPS32\x64\Release\my_test.exe