version: '0.3.0.{build}'

branches:
  only:
    - master
    - develop

configuration:
  - Debug
  - Release

platform:
  - Win32
  - x64

image: Visual Studio 2017

before_build:
- cmd: |-
    mkdir build
    cmake --version
    cmake . -Bbuild -G "Visual Studio 15 2017" -A%platform%
    cmake --build build --config %configuration%

build:
  project: c:\projects\MIPS32\build\MIPS32.sln
  verbosity: minimal
  parallel: true

test_script:
  - cmd: cd build && ctest -C %configuration% --output-on-failure