version: '0.1.0.{build}'

branches:
  only:
    - master
    - develop

configuration:
  - Debug
  - Release

platform:
  - x86
  - x64

image: Visual Studio 2017

before_build:
- cmd: |-
    mkdir build
    cd build
    cmake --version
    cmake .. -G "Visual Studio 15 2017" -A %configuration%
#    if ($env:PLATFORM -eq "x64") { cmake .. -G "Visual Studio 15 2017 Win64" }
#    else { cmake .. -G "Visual Studio 15 2017" }

build:
  project: c:\projects\MIPS32\build\MIPS32.sln
  verbosity: minimal
  parallel: true

test_script:
  - cmd: c:\projects\MIPS32\build\%platform%\%configuration%\my_test.exe
