version: '0.2.0.{build}'

branches:
  only:
    - master
    - develop

configuration:
  - Debug
  - Release

platform:
  - Win32
  - x64

image: Visual Studio 2017

before_build:
- cmd: |-
    mkdir build
    cd build
    cmake --version
    cmake .. -G "Visual Studio 15 2017" -A%platform%

build:
  project: c:\projects\MIPS32\build\MIPS32.sln
  verbosity: minimal
  parallel: true

test_script:
  - cmd: ctest -C %configuration% --output-on-failure